//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arac()
        {
            this.Bakım = new HashSet<Bakım>();
        }
    
        public int AracID { get; set; }
        public string Plaka { get; set; }
        public string SaseNo { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string ModelYılı { get; set; }
        public string Km { get; set; }
        public string RuhsatNo { get; set; }
        public string MotorNo { get; set; }
        public string Yakıt { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bakım> Bakım { get; set; }
    }
}
