//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islem
    {
        public int IslemID { get; set; }
        public string Islem1 { get; set; }
        public string Tutar { get; set; }
        public Nullable<int> BakımID { get; set; }
    
        public virtual Bakım Bakım { get; set; }
    }
}
